- library/decoder.ts
- library/encoder.ts
- library/resource/query_builder.ts
- library/schema/data_types.ts
- library/schema/utils.ts
> Referencing individual namespaces instead of getting them from the namespaces list

- library/rdf.ts
- specs/engine.test.ts
- specs/rdf.test.ts
- specs/treeiterator.test.ts
> Implemented custom bindings factory

- .vscode/settings.json
- library/engine/query_engine.ts
- library/engine/query_resolvers.ts
- library/lens/query_builder.ts
- library/rdf.ts
- tests/engine.test.ts
- tests/lens.test.ts
- tests/test_deps.ts
- tests/test_utils.ts
> Added support for text/turtle format for quad queries

- docs/table-of-contents.json
- docs/v2/working-with-arrays.md
- examples/basic/arrays.ts
- examples/basic/deno.json
- library/encoder.ts
- library/lens/lens.ts
- library/lens/query_builder.ts
- library/lens/query_helper.ts
- library/lens/update_helper.ts
- library/schema/interface.ts
- library/schema/mod.ts
- tests/e2e/arrays.test.ts
- tests/schema.test.ts
- tests/test_deps.ts
> Added support for large array modifications

- library/lens/lens.ts
- library/schema/data_types.ts
- library/schema/mod.ts
- library/sparql/stringify.ts
- mod.ts
- tests/e2e/data_types.test.ts
- tests/sparql_tag.test.ts
> Added E2E tests for all data types

- library/decoder.ts
- library/lens/query_builder.ts
- library/lens/update_helper.ts
- library/sparql/mod.ts
- library/sparql/sparql_expression_builders.ts
- library/sparql/sparql_shared_builders.ts
- library/sparql/sparql_tag.ts
- library/sparql/sparql_update_builders.ts
- tests/decoder.test.ts
- tests/e2e/optional.test.ts
- tests/sparql_expression_builders.test.ts
- tests/sparql_update_builders.test.ts
- tests/test_deps.ts
> Added support for updating values of optional properties

- docs/table-of-contents.json
- docs/v2/inverse-properties.md
- examples/basic/deno.json
- examples/basic/inverse.ts
- library/lens/query_builder.ts
- library/schema/schema.ts
- library/schema/utils.ts
- tests/e2e/inverse.test.ts
- tests/schema.test.ts
- tests/test_utils.ts
> Added support for inverse properties

- docs/table-of-contents.json
- docs/v2/filtering.md
- library/engine/query_engine_proxy.ts
- library/lens/lens.ts
- library/lens/query_builder.ts
- library/lens/search_helper.ts
- library/rdf.ts
- library/schema/interface.ts
- library/schema/mod.ts
- library/schema/search.ts
- tests/e2e/search.test.ts
- tests/schema.test.ts
> Added support for filtering results

- docs/components/schema.md
- docs/v2/inverse-properties.md
- examples/basic/inverse.ts
- examples/react-bulletin-boards/src/store.ts
- library/decoder.ts
- library/encoder.ts
- library/lens/query_builder.ts
- library/lens/query_helper.ts
- library/schema/interface.ts
- library/schema/schema.ts
- library/schema/utils.ts
- tests/decoder.test.ts
- tests/e2e/inverse.test.ts
- tests/encoder.test.ts
- tests/lens_common.test.ts
- tests/performance/scenario2.ts
- tests/schema.test.ts
> Replaced `@context` key in schema with `@schema`

- deno.json
- library/lens/lens.ts
- library/lens/query_builder.ts
- library/options.ts
- tests/e2e.test.ts
- tests/test_utils.ts
> Added support for custom query logger

- tests/e2e/dbpedia.test.ts
- tests/e2e/multilang.test.ts
- tests/lens_common.test.ts
- tests/test_utils.ts
> Added E2E tests for multilang feature

- library/decoder.ts
- library/encoder.ts
- library/lens/lens.ts
- library/lens/query_builder.ts
- library/lens/search_helper.ts
- library/lens/types.ts
- library/lens/update_helper.ts
- library/schema/interface.ts
- library/schema/mod.ts
- library/schema/schema.ts
- library/schema/utils.ts
- tests/decoder.test.ts
- tests/encoder.test.ts
- tests/schema.test.ts
> Refactored TypeScript types for better DX

- tests/e2e/rdf_types.test.ts
- www/data/docs.ts
> Added tests for `rdf:type` related queries

- README.md
> Added information about compliance with existing W3C standards

- .github/workflows/deno-test.yml
- .github/workflows/npm-publish.yml
- library/asynciterator.ts
- library/engine/types.ts
- library/lens/lens.ts
- library/lens/query_builder.ts
- library/rdf.ts
- tests/e2e/dbpedia.test.ts
- tests/test_deps.ts
- tests/test_utils.ts
- www/routes/_404.tsx
- www/routes/api/[...slug].tsx
- www/routes/docs/[...slug].tsx
Upgraded @rdfjs/types and all related dependencies to latest versions.
Upgraded workflow actions to use Deno v2 and Node.js v20.
> Upgraded @rdfjs/types to v2

- www/routes/api/[...slug].tsx
- www/routes/docs/[...slug].tsx
> Fixed www docs and api links not working in new Deno

- examples/basic/arrays.ts
- examples/react-bulletin-boards/package.json
- examples/react-bulletin-boards/src/store.ts
- examples/react-dbpedia-actors/package.json
- examples/react-dbpedia-actors/src/store.ts
- examples/react-dbpedia-actors/vite.config.ts
- examples/react-query-todo-app/package.json
- examples/react-query-todo-app/src/components/Add.tsx
- examples/react-query-todo-app/src/store.ts
- examples/react-query-todo-app/vite.config.ts
> Updated examples to latest version

- library/engine/query_engine.ts
> Conform to SPARQL 1.1 Protocol for update queries

- tests/test_utils.ts
- www/fresh.gen.ts
- www/routes/ontology/IRI.tsx
- www/routes/ontology/Resource.tsx
- www/routes/ontology/index.tsx
> Added LDkit ontology web pages

- library/engine/query_engine_proxy.ts
- library/engine/query_resolvers.ts
- library/rdf.ts
- library/utils.ts
- tests/test_utils.ts
> Optimized data streaming when parsing RDF

- library/engine/query_resolvers.ts
> Support N-Triples, N-Quads and TriG RDF formats

- library/engine/query_engine.ts
> Use `application/sparql-update` MIME type for updates

- docs/components/query-engine.md
- www/routes/docs/[...slug].tsx
Fixed not found and redirect issues
> Updated URL redirects in documentation

- library/asynciterator.ts
- library/engine/types.ts
- library/rdf.ts
- library/utils.ts
> Updated dependencies
